server:
  port: 7001
spring:
  profiles:
    active: dev
  application:
    name: service-provider-7001
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.1.15:8848
  redis:
    host: 192.168.1.15
    password:
    timeout: 5000
    lettuce:
      pool:
        max-wait: 10000
        max-active: 10
        max-idle: 5
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/online_shop?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:

management: ##暴露监控端点，此时curl -X POST "http://localhost:3355/actuator/refresh" 进行刷新即可同步最新配置
  endpoints:
    web:
      exposure:
        include: "*"

#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.own.common.pojo
  configuration:
    map-underscore-to-camel-case: true